### ISSUE TITLE
Rename env variable IPFS_REUSEPORT

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/go-tcp-transport#26]
This is libp2p, not IPFS specific, so it would be nice if it was called `LIBP2P_REUSEPORT` or even more specific `LIBP2P_TCP_REUSEPORT`.

**Comment by raulk** [comment]
@dignifiedquire do we want to assume some level of backwards compatibility, perhaps until [1.0.0](https://github.com/libp2p/libp2p/pull/39/)?
