### ISSUE TITLE
Reuseport reconnect delay

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-tcp-transport#37]
For some reason, reuseport is causing reconnects to be _delayed_ by 15 seconds, at least on localhost on my machine. This, of course, causes the reconnect to _fail_ because our timeout is 5 seconds.

**Comment by marten-seemann** [comment]
This might because you can't reuse the port until the TCP connection is actually gone, and not in TIME_WAIT any more. See https://github.com/libp2p/go-reuseport-transport/pull/42 for a more detailed explanation.
