### ISSUE TITLE
Build failure: type reuseport.Dialer has no field or method DialContext

### ISSUE THREAD

**Issue by shazow** [libp2p/go-tcp-transport#6]
```
github.com/libp2p/go-libp2p-swarm $ go version
go version go1.7.1 darwin/amd64
github.com/libp2p/go-libp2p-swarm $ go build
# github.com/libp2p/go-tcp-transport
../go-tcp-transport/tcp.go:196: d.rd.DialContext undefined (type reuseport.Dialer has no field or method DialContext)
```

Also doesn't look like travisci actually bothers trying to build the code.

**Comment by Kubuxu** [comment]
It is because we are using non official go-reuseport. Run `gx test` instead as it will use gx version of the dependency.

**Comment by shazow** [comment]
It's my understanding that libp2p things should be buildable without gx, correct? Should this issue be renamed/moved elsewhere?

**Comment by Kubuxu** [comment]
cc @whyrusleeping

**Comment by Kubuxu** [comment]
Fixed by merge of https://github.com/jbenet/go-reuseport/pull/17
