### ISSUE TITLE
Hit > 80% code coverage

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-tcp-transport#7]
Also related, #4

**Comment by Kubuxu** [comment]
We should switch this repo to codecov.

**Comment by theobat** [comment]
I'm building tests for this (a good way to get a better understanding),  trying for: 
- [Dialer](https://coveralls.io/builds/10752140/source?filename=tcp.go#L39)
- [ReuseDial](https://coveralls.io/builds/10752140/source?filename=tcp.go#L204)

I'm putting this in tcp_test.go but perhaps this needs a better splitting strategy ? Let me know if I need to be aware of anything specific (can help you to fix travis as well but have zero knowledge of the tool so.. might be an empty offer)
